### ISSUE TITLE
[FR] Console app example

### ISSUE THREAD

**Issue by pm64** [VMelnalksnis/PaperlessDotNet#147]
**Is your feature request related to a problem? Please describe.**
The README discusses usage outside of ASP.NET Core, and refers to "the configuration", which is a link to ServiceCollectionExtensions.cs in the VMelnalksnis.PaperlessDotNet.DependencyInjection package. It's not clear how this information should be used.

**Describe the solution you'd like**
A sample project in the form of a console app would be ideal, since this strips away any unnecessary layers that could obscure proper usage.

**Describe alternatives you've considered**
If not a sample project, perhaps some additional language could be added to the README that provides a little more information about the intended setup.

**Additional context**
None

**Comment by VMelnalksnis** [comment]
`ServiceCollectionExtensions` contains all the configuration needed to create a new `PaperlessClient` besides instantiating the required classes. A minimal example would look something like this:
```csharp
// todo read this from args/some config source
var options = new PaperlessOptions
{
	BaseAddress = new("http://localhost:8080"),
	Token = "token",
};

var assemblyName = typeof(IPaperlessClient).Assembly.GetName();
var assemblyShortName = assemblyName.Name ?? assemblyName.FullName.Split(',').First();

var httpClient = new HttpClient { BaseAddress = options.BaseAddress };
httpClient.DefaultRequestHeaders.UserAgent.Add(new(assemblyShortName, assemblyName.Version?.ToString()));
httpClient.DefaultRequestHeaders.Add("Accept", $"{MediaTypeNames.Application.Json}; version=2");
httpClient.DefaultRequestHeaders.Authorization = new("Token", options.Token);

var serializerOptions = new PaperlessJsonSerializerOptions(DateTimeZoneProviders.Tzdb);
var correspondentClient = new CorrespondentClient(httpClient, serializerOptions);
var documentClient = new DocumentClient(httpClient, serializerOptions);

var paperlessClient = new PaperlessClient(correspondentClient, documentClient);
```

You can probably also skip the user agent part, I don't recall it being required for Paperless. 

I'll see if I can add an integration test that is setup without using dependency injection, and link to that in the README instead.

**Comment by pm64** [comment]
Thank you @VMelnalksnis! This is similar to what I hacked together, but nice to have a definitive reference. Very grateful for your help.
