### ISSUE TITLE
Error parsing timestamp

### ISSUE THREAD

**Issue by pm64** [VMelnalksnis/PaperlessDotNet#148]
**Describe the bug**
API request appears to fail due to a timestamp parsing error.

**To Reproduce**

1. Execute the following test:

```
            var baseAddress = new Uri("http://paperless_host");
            var token = "your-token-here";

            var assemblyName = typeof(IPaperlessClient).Assembly.GetName();
            var assemblyShortName = assemblyName.Name ?? assemblyName.FullName.Split(',').First();
            ProductInfoHeaderValue userAgent = new(assemblyShortName, assemblyName.Version?.ToString());

            var client = new HttpClient
            {
                BaseAddress = baseAddress
            };

            client.DefaultRequestHeaders.UserAgent.Add(userAgent);

#if NET6_0_OR_GREATER
            client.DefaultRequestHeaders.Add("Accept", $"{MediaTypeNames.Application.Json}; version=2");
#else
			client.DefaultRequestHeaders.Add("Accept", "application/json; version=2");
#endif
            client.DefaultRequestHeaders.Authorization = new("Token", token);

            var dtz = DateTimeZoneProviders.Tzdb;
            var so = new PaperlessJsonSerializerOptions(dtz);
            var cc = new CorrespondentClient(client, so);

            var dc = new DocumentClient(client, so);

            var pc = new PaperlessClient(cc, dc);

            var docs = pc.Documents.GetAll();

            await foreach(var doc in docs)
            {
                Console.WriteLine(doc.OriginalFileName);
            }
```

2. Observe exception similar to the following:

```
System.Text.Json.JsonException: 'Cannot convert value to NodaTime.Instant'

Inner Exception
UnparsableValueException: The value string does not match a quoted string in the pattern. Value being parsed: '2023-12-18T00:00:00^-08:00'. (^ indicates error position.)
```

**Expected behavior**
A list of documents in the Paperless-ngx instance should be displayed

**Screenshots**
N/A

**Additional context**
N/A

**Comment by VMelnalksnis** [comment]
Which paperless version are you using? This package is tested against 1.9.2, so there might have been some changes

**Comment by pm64** [comment]
Indeed, I'm testing against 2.3.3. Is support for modern versions planned?

**Comment by VMelnalksnis** [comment]
Yes, I had started to work on testing against multiple paperless versions, I guess it's time to finally finish it. I'll see if I can reproduce the issue with that version.

**Comment by VMelnalksnis** [comment]
So looks like the issue is not the version, but `PAPERLESS_TIME_ZONE` because it also controls the API responses. From my testing looks like using `OffsetDateTime` instead of `Instant` for response models will fix the issue.

In order to test this I will have to add ability to add new documents to paperless, which complicates this fix a little bit. In v1.9.2 the create document endpoint simply starts the import task and returns `OK`, so it's not possible to reliably get the created document id. However, in newer versions it returns the task id, so it's possible the import result using the `/api/tasks/?task_id={uuid}` endpoint. I have a working solution, but I'm not yet sure how I'll add this to the package.

**Comment by pm64** [comment]
Sounds good @VMelnalksnis. I'm happy to assist with testing, just let me know what you need.

**Comment by pm64** [comment]
I just performed a quick test against the updated package and see this issue is now resolved!

Thank you @VMelnalksnis, excited to further explore this useful project.
