### ISSUE TITLE
[FR] Custom field support

### ISSUE THREAD

**Issue by pm64** [VMelnalksnis/PaperlessDotNet#152]
**Is your feature request related to a problem? Please describe.**
Somewhere along the line, Paperless-ngx added support for custom fields. Unless I'm missing something (usually the case), this feature is not currently supported by PaperlessDotNet.

**Describe the solution you'd like**
It should be possible to specify custom fields and values at document creation time, to read custom fields from documents that have been retrieved, and to retrieve an instance's current set of custom fields.

**Describe alternatives you've considered**
There is no apparent workaround or alternative solution.

**Additional context**
N/A

**Comment by VMelnalksnis** [comment]
Since this is only available in some versions, I think the best way will be to add overloads the the Get/GetAll methods with a `TFields` generic parameter so that the custom fields can be strongly typed. Another option would to just add `Dictionary<string, object>`, but I'd like to avoid that if possible.

I don't see anything in the documentation or the API specification on how to set the custom fields though. If you could provide a working example request that creates a document with custom fields, that would be great. Also, since the document creation endpoint only supports multipart/form-data instead of JSON, right now I don't see how to implement it without using reflection.

For reference, here's a list of supported data types for custom fields:
```json
            "data_type": {
                "type": "choice",
                "required": true,
                "read_only": false,
                "label": "Data type",
                "choices": [
                    {
                        "value": "string",
                        "display_name": "string"
                    },
                    {
                        "value": "url",
                        "display_name": "url"
                    },
                    {
                        "value": "date",
                        "display_name": "date"
                    },
                    {
                        "value": "boolean",
                        "display_name": "boolean"
                    },
                    {
                        "value": "integer",
                        "display_name": "integer"
                    },
                    {
                        "value": "float",
                        "display_name": "float"
                    },
                    {
                        "value": "monetary",
                        "display_name": "monetary"
                    },
                    {
                        "value": "documentlink",
                        "display_name": "documentlink"
                    }
                ]
            }
```

**Comment by VMelnalksnis** [comment]
Well, the API feels like such a mess - even the API browser does not match the actual behavior/supported HTTP methods. Anyway, I expected the custom fields to be returned in some format that would be parsable as JSON, something like:
```json
"custom_fields": {
    "field1": "foo bar",
    "field2": true,
    "field3": "2023-11-08",
    "field4": "https://example.com/"
}
```
But instead it returns it like this, where `field` is the id of the custom field:
```json
"custom_fields": [
    {
        "value": "foo bar",
        "field": 1
    },
    {
        "value": true,
        "field": 2
    },
    {
        "value": "2023-11-08",
        "field": 3
    },
    {
        "value": "https://example.com/",
        "field": 7
    }
]
```
It looks like a pain to work with such a response. The alternative would be to store the custom field definitions, and then using those do a second pass deserialization to map this list to a proper object. Implementing `JsonConverter` with global state sounds fun though 😄.

Also, custom fields cannot be set when creating the document. They only can be set by updating the document via PATCH afterwards.

**Comment by pm64** [comment]
Hey @VMelnalksnis, I just finished reading your PR, looks fantastic! I see that more work is needed to support bools (and another key data type, "document link", which is actually a collection), but you're well past a solid foundation.

I'm new in the world of Paperless-ngx and haven't yet been scuba diving in the API. But sounds like a battle. Very grateful to you for abstracting it away :)

My offer to assist with testing etc. stands. Sorry I couldn't get back to you sooner on the example request you asked for.

**Comment by VMelnalksnis** [comment]
@pm64 Can you take a look at these tests and see if it covers everything you would need to do with custom fields? https://github.com/VMelnalksnis/PaperlessDotNet/pull/154/files#diff-240c7203f520bf8d42cf450a611c1bdc178b5f80afecdacff6644cc2f0aa7dc1R104

I think the client looks done if that's all of the needed functionality, but I'll need to clean up the tests and configuration.
