### ISSUE TITLE
Tag GetAll-Method fails

### ISSUE THREAD

**Issue by stefanvogelch** [VMelnalksnis/PaperlessDotNet#276]
HI VMelnalksnis

paperlessClient.Tags.GetAll() fails, if "matching_algorithm" is set to 0 (Zero)
Exception: System.Text.Json.JsonException: "Error converting value '0' to a smart enum."
Inner Exception: SmartEnumNotFoundException: No MatchingAlgorithm with Value 0 found.

Release 1.0.0, Paperlesss 2.8.6

Kind regards, Stefan

**Comment by VMelnalksnis** [comment]
Looks like it's missing `None` option, will add it

**Comment by stefanvogelch** [comment]
Great, Thanks. Be aware, this is also an issue with correspondents (and maybe other elements).

**Comment by VMelnalksnis** [comment]
There is only one definition of matching algorithms, so it should be fixed for all endpoints.
